name: Fork Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # every month

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fork Sync
        uses: tgymnich/fork-sync@v1.2.1
        with:
          owner: defautluser0
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          head: main
          base: main
          pr_title: Automatic fork sync
          pr_message: Done by an action
